name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check code formatting
        run: pnpm format:check

      - name: Run linter
        run: pnpm lint

      - name: Build packages
        run: pnpm build
