name: Publish
on:
  workflow_dispatch:
    inputs:
      segment:
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
        required: true
      access:
        type: choice
        options:
          - public
          - restricted
        required: true
jobs:
  increment-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update version
        id: version
        run: |
          old=$(npm version)
          new=$(npm version ${{ inputs.segment }} --no-git-tag-version)
          pnpm -r exec "npm version ${new} --no-git-tag-version"
          git tag versions/${new}
          echo "old=${old}" >> "$GITHUB_OUTPUT"
          echo "new=${new}" >> "$GITHUB_OUTPUT"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "(chore): Update version ${{ steps.version.outputs.old }} -> ${{ steps.version.outputs.new }}"
          title: "(chore): Update version ${{ steps.version.outputs.old }} -> ${{ steps.version.outputs.new }}"

      - name: Build packages
        run: pnpm build

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish -r --access ${{inputs.access}}